/**
 * Typed catalog of every Ancher API error code.
 *
 * GENERATED FILE — do not edit by hand. Regenerate with
 * `node scripts/generate-error-codes.mjs` (parses the backend's app/errors.py).
 *
 * Codes follow `API-XXYZZZ`: a 2–3 char module, a 1 char layer, a 3 digit
 * sequence. Use {@link getErrorDefinition} / {@link AncherApiError.definition}
 * to resolve a code to its canonical message + HTTP status, and
 * {@link ApiErrorCodes} for ergonomic, autocompleted references to specific codes.
 */

/** Canonical definition of a single API error code. */
export interface ApiErrorDefinition {
  /** The backend enum identifier, e.g. `BILLING_INSUFFICIENT_CREDITS`. */
  name: string
  /** Human-readable default message. */
  message: string
  /** HTTP status the backend returns with this code. */
  status: number
}

/** Every error code the API can return, mapped to its canonical definition. */
export const API_ERROR_DEFINITIONS = {
  'API-AFR001': { name: 'ARTIFACT_NOT_FOUND', message: 'Artifact not found', status: 404 },
  'API-AFS001': { name: 'ARTIFACT_CREATION_FAILED', message: 'Failed to create artifact', status: 500 },
  'API-AFS002': { name: 'ARTIFACT_CONTENT_NOT_TEXT', message: 'Artifact content is not text; use the presigned download URL', status: 400 },
  'API-AIS001': { name: 'OCR_AGENT_FAILED', message: 'AI agent processing failed', status: 502 },
  'API-AIS003': { name: 'AI_MODEL_UNAVAILABLE', message: 'AI model unavailable', status: 503 },
  'API-AIS004': { name: 'AI_RATE_LIMIT', message: 'AI service rate limit exceeded', status: 429 },
  'API-AIS007': { name: 'KEYFRAME_EXTRACTION_FAILED', message: 'Keyframe extraction agent failed', status: 502 },
  'API-AIS008': { name: 'FRAME_EXTRACTION_FAILED', message: 'Frame extraction from video failed', status: 500 },
  'API-AIS009': { name: 'IMAGE_DESCRIPTION_FAILED', message: 'Image description agent failed', status: 502 },
  'API-AIS010': { name: 'TAG_GENERATION_FAILED', message: 'Tag generation agent failed', status: 502 },
  'API-AIS011': { name: 'MULTIMODAL_EMBEDDING_FAILED', message: 'Multimodal embedding failed', status: 502 },
  'API-AIS012': { name: 'PLAN_AGENT_BUDGET_EXHAUSTED', message: 'Plan agent exceeded its request budget; returning fallback plan', status: 502 },
  'API-AIS013': { name: 'MAIN_AGENT_BUDGET_EXHAUSTED', message: 'Main agent exceeded its request budget; ending turn with fallback reply', status: 502 },
  'API-AKR001': { name: 'API_KEY_NOT_FOUND', message: 'API key not found', status: 404 },
  'API-ATR001': { name: 'ARTICLE_NOT_FOUND', message: 'Article not found', status: 404 },
  'API-ATR002': { name: 'ARTICLE_ACCESS_DENIED', message: 'Access denied to article', status: 403 },
  'API-ATR003': { name: 'ARTICLE_INVALID_INPUT', message: 'Invalid input for article', status: 400 },
  'API-ATS001': { name: 'ARTICLE_CREATION_FAILED', message: 'Failed to create article', status: 500 },
  'API-ATS002': { name: 'ARTICLE_PARSING_FAILED', message: 'Failed to parse article', status: 500 },
  'API-ATS003': { name: 'ARTICLE_UPDATE_FAILED', message: 'Failed to update article', status: 500 },
  'API-ATS004': { name: 'ARTICLE_DELETION_FAILED', message: 'Failed to delete article', status: 500 },
  'API-AUR001': { name: 'AUTH_TOKEN_MISSING', message: 'Authentication token missing', status: 401 },
  'API-AUR002': { name: 'AUTH_TOKEN_INVALID', message: 'Invalid authentication token', status: 401 },
  'API-AUR003': { name: 'AUTH_TOKEN_EXPIRED', message: 'Authentication token expired', status: 401 },
  'API-AUR004': { name: 'AUTH_PERMISSION_DENIED', message: 'Permission denied', status: 403 },
  'API-AUR005': { name: 'AUTH_RESOURCE_FORBIDDEN', message: 'Access to resource forbidden', status: 403 },
  'API-AUR006': { name: 'AUTH_CSRF_MISSING', message: 'CSRF token missing', status: 403 },
  'API-AUR007': { name: 'AUTH_CSRF_INVALID', message: 'CSRF token invalid', status: 403 },
  'API-AUR008': { name: 'AUTH_SESSION_REQUIRED', message: 'This endpoint requires an interactive session', status: 403 },
  'API-BIC001': { name: 'BILLING_PROVIDER_NOT_ENABLED', message: 'Payment provider unavailable', status: 503 },
  'API-BIR001': { name: 'BILLING_WEBHOOK_SIGNATURE_INVALID', message: 'Webhook signature invalid', status: 401 },
  'API-BIR002': { name: 'BILLING_WEBHOOK_EVENT_DUPLICATE', message: 'Webhook event already processed', status: 200 },
  'API-BIS001': { name: 'BILLING_PAYMENT_PROCESSING_FAILED', message: 'Payment processing failed', status: 502 },
  'API-BIS002': { name: 'BILLING_INSUFFICIENT_CREDITS', message: 'Insufficient credits', status: 402 },
  'API-BIS003': { name: 'BILLING_PLAN_NOT_FOUND', message: 'Plan not found', status: 404 },
  'API-BIS004': { name: 'BILLING_SUBSCRIPTION_NOT_FOUND', message: 'Subscription not found', status: 404 },
  'API-BIS005': { name: 'BILLING_PRODUCT_COST_NOT_FOUND', message: 'Product cost missing for product at requested time', status: 500 },
  'API-BIS006': { name: 'BILLING_DISCOUNT_CODE_NOT_FOUND', message: 'Discount code not found', status: 404 },
  'API-BIS007': { name: 'BILLING_DISCOUNT_CODE_EXPIRED', message: 'Discount code expired', status: 410 },
  'API-BIS008': { name: 'BILLING_DISCOUNT_CODE_ALREADY_REDEEMED', message: 'Discount code already redeemed', status: 409 },
  'API-BIS009': { name: 'BILLING_DISCOUNT_CODE_EXHAUSTED', message: 'Discount code redemption limit reached', status: 410 },
  'API-BIS010': { name: 'BILLING_CUSTOMER_NOT_FOUND', message: 'No billing account to manage', status: 404 },
  'API-BIS011': { name: 'BILLING_INVALID_RETURN_URL', message: 'return_url is not an allowed origin', status: 400 },
  'API-BIS012': { name: 'BILLING_PLAN_CHANGE_INVALID', message: 'Plan change is not allowed (price and credits must move together)', status: 400 },
  'API-BIS013': { name: 'BILLING_CHECKOUT_SESSION_NOT_FOUND', message: 'Checkout session not found', status: 404 },
  'API-BIS014': { name: 'BILLING_PURCHASE_TOKEN_INVALID', message: 'Purchase token invalid', status: 400 },
  'API-BIS015': { name: 'BILLING_PURCHASE_VERIFICATION_FAILED', message: 'Purchase verification failed', status: 502 },
  'API-BIS016': { name: 'BILLING_SUBSCRIPTION_CONFLICT', message: 'A paid subscription already exists', status: 409 },
  'API-BIS017': { name: 'BILLING_PLAN_DOWNGRADE_NOT_SUPPORTED', message: 'Only upgrades are available while subscribed', status: 400 },
  'API-CDN001': { name: 'CDN_SIGNER_UNAVAILABLE', message: 'Failed to generate download URL', status: 500 },
  'API-CFC001': { name: 'CONFIG_MISSING', message: 'Required configuration missing', status: 500 },
  'API-CFC002': { name: 'CONFIG_INVALID', message: 'Invalid configuration value', status: 500 },
  'API-CLR001': { name: 'COLLECTION_NOT_FOUND', message: 'Collection not found', status: 404 },
  'API-CLR002': { name: 'COLLECTION_ACCESS_DENIED', message: 'Access denied to collection', status: 403 },
  'API-CLR003': { name: 'COLLECTION_ALREADY_EXISTS', message: 'Collection already exists', status: 409 },
  'API-CLS001': { name: 'COLLECTION_CREATION_FAILED', message: 'Failed to create collection', status: 500 },
  'API-CLS002': { name: 'COLLECTION_UPDATE_FAILED', message: 'Failed to update collection', status: 500 },
  'API-CLS003': { name: 'COLLECTION_DELETION_FAILED', message: 'Failed to delete collection', status: 500 },
  'API-CVR001': { name: 'CONVERSATION_NOT_FOUND', message: 'Conversation not found', status: 404 },
  'API-CVR002': { name: 'MESSAGE_NOT_FOUND', message: 'Message not found', status: 404 },
  'API-CVR003': { name: 'CONVERSATION_ACCESS_DENIED', message: 'Access denied to conversation', status: 403 },
  'API-CVR004': { name: 'MESSAGE_ACCESS_DENIED', message: 'Access denied to message', status: 403 },
  'API-CVR005': { name: 'CONVERSATION_INVALID_CURSOR', message: 'Invalid cursor for conversation pagination', status: 400 },
  'API-CVR006': { name: 'MESSAGE_INVALID_CURSOR', message: 'Invalid cursor for message pagination', status: 400 },
  'API-CVS001': { name: 'CONVERSATION_CREATION_FAILED', message: 'Failed to create conversation', status: 500 },
  'API-CVS002': { name: 'CONVERSATION_UPDATE_FAILED', message: 'Failed to update conversation', status: 500 },
  'API-CVS003': { name: 'CONVERSATION_DELETION_FAILED', message: 'Failed to delete conversation', status: 500 },
  'API-CVS004': { name: 'MESSAGE_CREATION_FAILED', message: 'Failed to create message', status: 500 },
  'API-CVS005': { name: 'MESSAGE_UPDATE_FAILED', message: 'Failed to update message', status: 500 },
  'API-CVS006': { name: 'MESSAGE_DELETION_FAILED', message: 'Failed to delete message', status: 500 },
  'API-CVS007': { name: 'MESSAGE_HISTORY_RETRIEVAL_ERROR', message: 'Failed to retrieve message history', status: 500 },
  'API-CVS008': { name: 'LLM_STREAMING_ERROR', message: 'LLM streaming error occurred', status: 502 },
  'API-CVS009': { name: 'LLM_API_FAILURE', message: 'LLM API request failed', status: 502 },
  'API-CVS010': { name: 'CONVERSATION_RUN_IN_PROGRESS', message: 'Conversation already has an active run', status: 409 },
  'API-CVS011': { name: 'MESSAGE_MENTION_MIXED', message: 'A message can mention either one collection or notes/artifacts, not both', status: 400 },
  'API-CVS012': { name: 'MESSAGE_MENTION_TOO_MANY_COLLECTIONS', message: 'A message can mention at most one collection', status: 400 },
  'API-CVS013': { name: 'MESSAGE_MENTION_LIMIT_EXCEEDED', message: 'A message can mention at most 5 notes and artifacts combined', status: 400 },
  'API-CVS014': { name: 'CLARIFICATION_NOT_FOUND', message: 'Clarification request not found', status: 404 },
  'API-CVS015': { name: 'CLARIFICATION_CANCELLED', message: 'Clarification request was cancelled', status: 409 },
  'API-CVS016': { name: 'CLARIFICATION_RUN_INACTIVE', message: 'Clarification request is no longer active', status: 409 },
  'API-CVS017': { name: 'CONVERSATION_NO_ACTIVE_RUN', message: 'No active run to interrupt', status: 409 },
  'API-CVS018': { name: 'CONVERSATION_RUN_LOST', message: 'Conversation run was lost before completing', status: 500 },
  'API-CVV001': { name: 'CONVERSATION_NAME_TOO_LONG', message: 'Conversation name exceeds maximum length', status: 400 },
  'API-CVV002': { name: 'CONVERSATION_NAME_EMPTY', message: 'Conversation name cannot be empty', status: 400 },
  'API-CVV003': { name: 'MESSAGE_EMPTY', message: 'Message content cannot be empty', status: 400 },
  'API-CVV004': { name: 'MESSAGE_ROLE_INVALID', message: 'Invalid message role (must be user or assistant)', status: 400 },
  'API-CVV005': { name: 'MESSAGE_TOO_LONG', message: 'Message content exceeds maximum length', status: 400 },
  'API-CVV006': { name: 'CONVERSATION_SERVER_ERROR', message: 'Server error when streaming conversation', status: 500 },
  'API-CVV007': { name: 'CLARIFICATION_INVALID_RESPONSE', message: 'Clarification response is invalid', status: 400 },
  'API-DBA001': { name: 'DB_QUERY_NOT_SELECT', message: 'Only SELECT queries are allowed', status: 400 },
  'API-DBA003': { name: 'DB_TABLE_PROHIBITED', message: 'Access to table is prohibited', status: 403 },
  'API-DBA004': { name: 'DB_TABLE_UNKNOWN', message: 'Table not recognized or not allowed', status: 400 },
  'API-DBA005': { name: 'DB_QUERY_MIXED_FILTER_TABLES', message: 'Cannot mix user_preferences/user_demographics with other tables', status: 400 },
  'API-DBA006': { name: 'DB_QUERY_INVALID_FILTER', message: 'Query has invalid user filter', status: 400 },
  'API-DBA007': { name: 'DB_QUERY_EXECUTION_FAILED', message: 'Query execution failed', status: 500 },
  'API-DBA008': { name: 'DB_QUERY_UNEXPECTED_ERROR', message: 'Unexpected error during query execution', status: 500 },
  'API-DBC001': { name: 'DB_CONNECTION_FAILED', message: 'Database connection failed', status: 503 },
  'API-DBC002': { name: 'DB_TIMEOUT', message: 'Database operation timed out', status: 504 },
  'API-DBC003': { name: 'DB_CURSOR_INVALID_ORDER', message: 'Cursor pagination only supports ordering by id field', status: 400 },
  'API-DBM001': { name: 'DB_TRANSACTION_FAILED', message: 'Database transaction failed', status: 500 },
  'API-DBM002': { name: 'DB_CONSTRAINT_VIOLATION', message: 'Database constraint violation', status: 409 },
  'API-DBM003': { name: 'DB_RECORD_NOT_FOUND', message: 'Database record not found', status: 404 },
  'API-ECC001': { name: 'EXTERNAL_CONNECTION_DECRYPTION_FAILED', message: 'Failed to decrypt stored credentials', status: 500 },
  'API-ECR001': { name: 'EXTERNAL_CONNECTION_PROVIDER_NOT_REGISTERED', message: 'Unknown external-connection provider', status: 400 },
  'API-ECR002': { name: 'EXTERNAL_CONNECTION_NOT_FOUND', message: 'External connection not found', status: 404 },
  'API-ECR003': { name: 'EXTERNAL_CONNECTION_INVALID_CALLBACK', message: 'Malformed OAuth callback', status: 400 },
  'API-ECS001': { name: 'EXTERNAL_CONNECTION_STATE_INVALID', message: 'Authorization state is invalid, expired, or already used', status: 400 },
  'API-ECS003': { name: 'EXTERNAL_CONNECTION_PROVIDER_REFRESH_FAILED', message: 'Provider rejected the refresh token; re-auth required', status: 401 },
  'API-ECS004': { name: 'EXTERNAL_CONNECTION_INVALID_GRANT', message: 'Provider rejected the authorization code', status: 400 },
  'API-ECS005': { name: 'EXTERNAL_CONNECTION_DISABLED', message: 'External-connection storage is disabled in this environment', status: 503 },
  'API-ECS006': { name: 'EXTERNAL_CONNECTION_NOT_ACTIVE', message: 'Connection is not active; reconnect required', status: 409 },
  'API-ECS007': { name: 'EXTERNAL_CONNECTION_REFRESH_UNAVAILABLE', message: 'Token refresh temporarily unavailable; retry later', status: 503 },
  'API-ECS008': { name: 'EXTERNAL_CONNECTION_AMBIGUOUS', message: 'Multiple active external connections found', status: 409 },
  'API-ECS009': { name: 'EXTERNAL_CONNECTION_ACCOUNT_UNAVAILABLE', message: 'Something went wrong. This account cannot be connected.', status: 409 },
  'API-EXS004': { name: 'EXTERNAL_SERVICE_TIMEOUT', message: 'External service timeout', status: 504 },
  'API-EXS005': { name: 'EXTERNAL_IMAGE_DOWNLOAD_FAILED', message: 'Failed to download image from external source', status: 502 },
  'API-EXS006': { name: 'DEEPINFRA_ERROR', message: 'DeepInfra API error', status: 502 },
  'API-EXS007': { name: 'EXTERNAL_FILE_DOWNLOAD_FAILED', message: 'Failed to download file from external source', status: 502 },
  'API-EXS008': { name: 'BRIGHTDATA_SCRAPE_FAILED', message: 'Bright Data scrape failed', status: 502 },
  'API-EXS009': { name: 'LINKEDIN_CONTENT_UNAVAILABLE', message: 'LinkedIn content is unavailable (private, removed, or login-gated)', status: 502 },
  'API-FLR001': { name: 'FILE_NOT_FOUND', message: 'File not found', status: 404 },
  'API-FLR002': { name: 'FILE_INVALID_FORMAT', message: 'Invalid file format', status: 400 },
  'API-FLR003': { name: 'FILE_MISSING_PARAMETER', message: 'Required file parameter missing', status: 400 },
  'API-FLS001': { name: 'FILE_S3_UPLOAD_FAILED', message: 'Failed to upload file to S3', status: 503 },
  'API-FLS002': { name: 'FILE_S3_DOWNLOAD_FAILED', message: 'Failed to download file from S3', status: 503 },
  'API-FLS003': { name: 'FILE_DB_SAVE_FAILED', message: 'Failed to save file metadata', status: 500 },
  'API-FLS004': { name: 'FILE_DB_DELETE_FAILED', message: 'Failed to delete file record', status: 500 },
  'API-FLS005': { name: 'FILE_S3_DELETE_FAILED', message: 'Failed to delete file from S3', status: 503 },
  'API-FLS006': { name: 'FILE_NOT_FOUND_IN_S3', message: 'File not found in S3', status: 404 },
  'API-FLS007': { name: 'FILE_SIZE_MISMATCH', message: 'File size mismatch between database and S3', status: 409 },
  'API-FLS008': { name: 'FILE_REVISION_NOT_FOUND', message: 'File revision not found', status: 404 },
  'API-FLS009': { name: 'FILE_REVISION_NOT_OWNED', message: 'Revision does not belong to this file', status: 400 },
  'API-FLS010': { name: 'FILE_NOT_REVISIONED', message: 'File does not support revisions', status: 400 },
  'API-FLV001': { name: 'FILE_TOO_LARGE', message: 'File exceeds maximum size limit', status: 413 },
  'API-FLV002': { name: 'FILE_EMPTY', message: 'File is empty', status: 400 },
  'API-FLV003': { name: 'FILE_TYPE_NOT_ALLOWED', message: 'File type not allowed', status: 415 },
  'API-FLV004': { name: 'FILE_NAME_INVALID', message: 'Invalid file name', status: 400 },
  'API-FLV005': { name: 'FILE_UPLOAD_NOT_COMPLETABLE', message: 'Upload is too old to complete; request a new upload URL', status: 410 },
  'API-FSR001': { name: 'FEISHU_USER_NOT_LINKED', message: 'Feishu user not linked to Ancher account', status: 401 },
  'API-FSR002': { name: 'FEISHU_SIGNATURE_INVALID', message: 'Feishu request signature invalid', status: 401 },
  'API-FSS001': { name: 'FEISHU_SAVE_FAILED', message: 'Failed to save messages', status: 500 },
  'API-FSS002': { name: 'FEISHU_SEARCH_FAILED', message: 'Search failed', status: 500 },
  'API-FSS003': { name: 'FEISHU_CHAT_FAILED', message: 'Chat failed', status: 500 },
  'API-FSS004': { name: 'FEISHU_NO_SESSION', message: 'No active session for linked user', status: 401 },
  'API-GRR001': { name: 'GRAPH_REQUEST_VALIDATION_FAILED', message: 'Graph request validation failed', status: 422 },
  'API-GRS001': { name: 'GRAPH_EXECUTION_FAILED', message: 'Graph execution failed', status: 500 },
  'API-GRS002': { name: 'GRAPH_NODE_TIMEOUT', message: 'Graph node timed out', status: 504 },
  'API-GRS003': { name: 'GRAPH_MAX_ITERATIONS_EXCEEDED', message: 'Graph exceeded maximum iterations', status: 500 },
  'API-IMG001': { name: 'IMG_UNKNOWN_TAXONOMY', message: 'Unknown style, layout, or palette slug', status: 400 },
  'API-IMG002': { name: 'IMG_PROVIDER_FAILED', message: 'Image generation provider call failed', status: 502 },
  'API-IMG003': { name: 'IMG_REFERENCE_NOT_FOUND', message: 'Reference image not found', status: 404 },
  'API-IMG004': { name: 'IMG_PROMPT_ASSEMBLY_FAILED', message: 'Prompt assembly failed', status: 500 },
  'API-INR001': { name: 'INSIGHT_NOT_FOUND', message: 'Insight not found', status: 404 },
  'API-INR002': { name: 'INSIGHT_ACCESS_DENIED', message: 'Access denied to this insight', status: 403 },
  'API-INR003': { name: 'INSIGHT_INVALID_TYPE', message: 'Invalid insight type', status: 400 },
  'API-INS001': { name: 'INSIGHT_GENERATION_FAILED', message: 'Failed to generate insight', status: 500 },
  'API-INS002': { name: 'INSIGHT_CREATION_FAILED', message: 'Failed to create insight record', status: 500 },
  'API-INS003': { name: 'INSIGHT_INSUFFICIENT_DATA', message: 'Insufficient data to generate insight', status: 400 },
  'API-INS004': { name: 'INSIGHT_UPDATE_FAILED', message: 'Failed to update insight', status: 500 },
  'API-INT001': { name: 'INTERNAL_VALIDATION_ERROR', message: 'Internal validation error', status: 500 },
  'API-IPS001': { name: 'IMAGE_PROMPT_GENERATION_FAILED', message: 'Image prompt generation failed', status: 502 },
  'API-IPS002': { name: 'IMAGE_PROMPT_IN_PROGRESS', message: 'Image prompt generation for this image is already in progress; retry shortly', status: 425 },
  'API-NOR001': { name: 'NOTE_NOT_FOUND', message: 'Note not found', status: 404 },
  'API-NOR002': { name: 'NOTE_ACCESS_DENIED', message: 'Access denied to note', status: 403 },
  'API-NOR003': { name: 'NOTE_INVALID_INPUT', message: 'Invalid input for note', status: 400 },
  'API-NOS001': { name: 'NOTE_CREATION_FAILED', message: 'Failed to create note', status: 500 },
  'API-NOS002': { name: 'NOTE_PARSING_FAILED', message: 'Failed to parse note', status: 500 },
  'API-NOS003': { name: 'NOTE_UPDATE_FAILED', message: 'Failed to update note', status: 500 },
  'API-NOS004': { name: 'NOTE_DELETION_FAILED', message: 'Failed to delete note', status: 500 },
  'API-NOS005': { name: 'NOTE_COPY_FAILED', message: 'Failed to copy note', status: 500 },
  'API-NTR001': { name: 'NOTIFICATION_NOT_FOUND', message: 'Notification not found', status: 404 },
  'API-NTR002': { name: 'NOTIFICATION_ACCESS_DENIED', message: 'Access denied to this notification', status: 403 },
  'API-NTS001': { name: 'NOTIFICATION_DISABLED', message: 'Notifications are disabled for this user', status: 403 },
  'API-NTS002': { name: 'NOTIFICATION_SEND_FAILED', message: 'Failed to send notification', status: 500 },
  'API-NTS003': { name: 'NOTIFICATION_NO_DEVICES', message: 'No devices found for notification', status: 404 },
  'API-O2R001': { name: 'OAUTH2_INVALID_CLIENT', message: 'Unknown or disabled OAuth2 client', status: 400 },
  'API-O2R002': { name: 'OAUTH2_INVALID_REDIRECT_URI', message: 'Redirect URI not registered for this client', status: 400 },
  'API-O2R003': { name: 'OAUTH2_INVALID_REQUEST', message: 'Malformed OAuth2 request', status: 400 },
  'API-O2R004': { name: 'OAUTH2_UNSUPPORTED_GRANT_TYPE', message: 'Unsupported OAuth2 grant_type', status: 400 },
  'API-O2R005': { name: 'OAUTH2_INVALID_STATE', message: 'Signed state is invalid, tampered, or expired', status: 400 },
  'API-O2R006': { name: 'OAUTH2_ACCESS_DENIED', message: 'User denied the authorization request', status: 403 },
  'API-O2S001': { name: 'OAUTH2_INVALID_GRANT', message: 'Authorization code is invalid, expired, or already used', status: 400 },
  'API-O2S002': { name: 'OAUTH2_PKCE_VERIFICATION_FAILED', message: 'PKCE code verifier does not match challenge', status: 400 },
  'API-O2S003': { name: 'OAUTH2_INVALID_CLIENT_SECRET', message: 'Client secret is missing or incorrect', status: 401 },
  'API-OAS001': { name: 'OAUTH_TOKEN_INVALID', message: 'Invalid OAuth token', status: 401 },
  'API-OAS002': { name: 'OAUTH_TOKEN_EXPIRED', message: 'OAuth token expired', status: 401 },
  'API-OAS003': { name: 'OAUTH_PROVIDER_ERROR', message: 'OAuth provider error', status: 502 },
  'API-OAS004': { name: 'OAUTH_VERIFICATION_FAILED', message: 'OAuth token verification failed', status: 401 },
  'API-OAS005': { name: 'OAUTH_EMAIL_MISSING', message: 'Email not provided by OAuth provider', status: 400 },
  'API-OAS006': { name: 'OAUTH_PROVIDER_NOT_CONFIGURED', message: 'OAuth provider not configured', status: 503 },
  'API-OAS007': { name: 'OAUTH_INVALID_ISSUER', message: 'Invalid token issuer', status: 401 },
  'API-OAS008': { name: 'OAUTH_INVALID_AUDIENCE', message: 'Invalid token audience', status: 401 },
  'API-OAS009': { name: 'OAUTH_INVALID_PROVIDER', message: 'Invalid or unsupported OAuth provider', status: 400 },
  'API-ONS001': { name: 'ONBOARDING_TASK_NOT_COMPLETED', message: 'Onboarding task has not been completed yet', status: 409 },
  'API-ONS002': { name: 'ONBOARDING_REWARD_ALREADY_CLAIMED', message: 'Onboarding reward already claimed', status: 409 },
  'API-PIR001': { name: 'PINNED_ITEM_NOT_FOUND', message: 'Pinned item not found', status: 404 },
  'API-PIR002': { name: 'PINNED_ITEM_ALREADY_EXISTS', message: 'Item is already pinned', status: 409 },
  'API-PIR003': { name: 'PINNED_ITEM_INVALID_INPUT', message: 'Invalid input for pinned item', status: 400 },
  'API-PPC001': { name: 'PPT_GAMMA_DISABLED', message: 'PPT generation is currently unavailable', status: 503 },
  'API-PPS001': { name: 'PPT_GAMMA_SUBMIT_FAILED', message: 'Failed to submit PPT generation request', status: 502 },
  'API-PPS003': { name: 'PPT_GAMMA_TIMEOUT', message: 'PPT generation timed out', status: 504 },
  'API-PPS004': { name: 'PPT_GAMMA_DOWNLOAD_FAILED', message: 'Failed to download generated PPT', status: 502 },
  'API-PYV001': { name: 'PYDANTIC_VALIDATION_ERROR', message: 'Request validation failed', status: 422 },
  'API-PYV002': { name: 'PYDANTIC_FIELD_REQUIRED', message: 'Required field missing', status: 422 },
  'API-PYV003': { name: 'PYDANTIC_TYPE_ERROR', message: 'Invalid field type', status: 422 },
  'API-PYV004': { name: 'PYDANTIC_VALUE_ERROR', message: 'Invalid field value', status: 422 },
  'API-RCR001': { name: 'RECOMMENDATION_NOT_FOUND', message: 'Recommendation not found', status: 404 },
  'API-RCS001': { name: 'RECOMMENDATION_GENERATION_FAILED', message: 'Failed to generate recommendations', status: 500 },
  'API-RCS002': { name: 'RECOMMENDATION_SEARCH_FAILED', message: 'Web search failed', status: 502 },
  'API-S3C001': { name: 'S3_CONNECTION_FAILED', message: 'S3 connection failed', status: 503 },
  'API-S3C002': { name: 'S3_BUCKET_NOT_FOUND', message: 'S3 bucket not found', status: 404 },
  'API-S3C003': { name: 'S3_ACCESS_DENIED', message: 'S3 access denied', status: 403 },
  'API-SKR001': { name: 'SLACK_USER_NOT_LINKED', message: 'Slack user not linked to Ancher account', status: 401 },
  'API-SKS001': { name: 'SLACK_LINK_FAILED', message: 'Failed to link Slack account', status: 500 },
  'API-SKS002': { name: 'SLACK_SAVE_FAILED', message: 'Failed to save messages', status: 500 },
  'API-SKS003': { name: 'SLACK_SEARCH_FAILED', message: 'Search failed', status: 500 },
  'API-SKS004': { name: 'SLACK_CHAT_FAILED', message: 'Chat failed', status: 500 },
  'API-SKS005': { name: 'SLACK_NO_SESSION', message: 'No active session for linked user', status: 401 },
  'API-SLS001': { name: 'SKILL_NOT_FOUND', message: 'Skill not found', status: 404 },
  'API-SLS002': { name: 'SKILL_INVALID_FILE', message: 'Invalid skill file', status: 400 },
  'API-SLS003': { name: 'SKILL_INVALID_OWNERSHIP', message: 'Skill ownership is invalid', status: 400 },
  'API-SUR001': { name: 'SUGGESTION_NOT_FOUND', message: 'Collection suggestion not found', status: 404 },
  'API-SUR002': { name: 'SUGGESTION_ACCESS_DENIED', message: 'Access denied to collection suggestion', status: 403 },
  'API-SUR003': { name: 'SUGGESTION_INVALID_STATUS', message: 'Invalid suggestion status filter', status: 400 },
  'API-SUR004': { name: 'SUGGESTION_STATUS_CONFLICT', message: 'Suggestion status conflicts with requested transition', status: 409 },
  'API-SUS001': { name: 'SUGGESTION_CLASSIFICATION_FAILED', message: 'Collection classification agent failed', status: 502 },
  'API-TGR001': { name: 'TAG_NOT_FOUND', message: 'Tag not found', status: 404 },
  'API-TGR002': { name: 'TAG_ALREADY_EXISTS', message: 'Tag already exists', status: 409 },
  'API-TGR003': { name: 'TAG_INVALID_INPUT', message: 'Invalid input for tag', status: 400 },
  'API-TGS001': { name: 'TAG_CREATION_FAILED', message: 'Failed to create tag', status: 500 },
  'API-TGS002': { name: 'TAG_DELETION_FAILED', message: 'Failed to delete tag', status: 500 },
  'API-TSS001': { name: 'TEXT_SELECTION_FAILED', message: 'Text selection action failed', status: 502 },
  'API-TXR001': { name: 'TEXT_EMPTY', message: 'Text content cannot be empty', status: 400 },
  'API-TXR002': { name: 'TEXT_INVALID_SOURCE_ID', message: 'Invalid source_id format', status: 400 },
  'API-TXS001': { name: 'TEXT_SPLITTING_FAILED', message: 'Failed to split text into chunks', status: 500 },
  'API-TXS002': { name: 'TEXT_EMBEDDING_FAILED', message: 'Failed to generate embeddings', status: 500 },
  'API-TXS003': { name: 'TEXT_MILVUS_INSERT_FAILED', message: 'Failed to insert embeddings into Milvus', status: 503 },
  'API-USC001': { name: 'USER_CLIENT_IP_UNAVAILABLE', message: 'Client IP information unavailable', status: 400 },
  'API-USR001': { name: 'USER_NOT_FOUND', message: 'User not found', status: 404 },
  'API-USR002': { name: 'USER_ALREADY_EXISTS', message: 'User already exists', status: 409 },
  'API-USR003': { name: 'USER_EMAIL_NOT_VERIFIED', message: 'Email not verified', status: 403 },
  'API-USR004': { name: 'USER_INVALID_CREDENTIALS', message: 'Invalid credentials', status: 401 },
  'API-USR005': { name: 'USER_ACCOUNT_DISABLED', message: 'Account is disabled', status: 403 },
  'API-USR006': { name: 'USER_SESSION_NOT_FOUND', message: 'Session not found', status: 404 },
  'API-USR007': { name: 'USER_DEMOGRAPHIC_NOT_FOUND', message: 'User demographics not found', status: 404 },
  'API-USR008': { name: 'USER_PREFERENCES_NOT_FOUND', message: 'User preferences not found', status: 404 },
  'API-USR009': { name: 'USER_OAUTH_REQUIRED', message: 'OAuth authentication required', status: 401 },
  'API-USR010': { name: 'USER_ACCOUNT_NOT_ACTIVATED', message: 'Account requires activation', status: 403 },
  'API-USR011': { name: 'USER_ALREADY_ACTIVATED', message: 'Account is already activated', status: 409 },
  'API-USS001': { name: 'USER_REGISTRATION_FAILED', message: 'User registration failed', status: 500 },
  'API-USS002': { name: 'USER_PASSWORD_HASH_FAILED', message: 'Password hashing failed', status: 500 },
  'API-USS003': { name: 'USER_TOKEN_GENERATION_FAILED', message: 'Token generation failed', status: 500 },
  'API-USS004': { name: 'USER_EMAIL_SEND_FAILED', message: 'Failed to send email', status: 503 },
  'API-USS005': { name: 'USER_VERIFICATION_CODE_EXPIRED', message: 'Verification code expired', status: 400 },
  'API-USS006': { name: 'USER_VERIFICATION_CODE_INVALID', message: 'Invalid verification code', status: 400 },
  'API-USS007': { name: 'USER_SESSION_EXPIRED', message: 'Session has expired', status: 401 },
  'API-USS008': { name: 'USER_REFRESH_TOKEN_INVALID', message: 'Invalid refresh token', status: 401 },
  'API-USS009': { name: 'USER_REFRESH_TOKEN_EXPIRED', message: 'Refresh token expired', status: 401 },
  'API-USS010': { name: 'USER_UPDATE_FAILED', message: 'Failed to update user', status: 500 },
  'API-USS011': { name: 'USER_DELETE_FAILED', message: 'Failed to delete user', status: 500 },
  'API-USS012': { name: 'DEVICE_NOT_FOUND', message: 'Device not found', status: 404 },
  'API-USS013': { name: 'USER_INVITATION_CODE_INVALID', message: 'Invalid invitation code', status: 400 },
  'API-USS014': { name: 'USER_INVITATION_LIMIT_REACHED', message: 'Invitation limit reached', status: 400 },
  'API-USS015': { name: 'USER_ACTIVATION_CODE_REQUIRED', message: 'Activation code is required', status: 400 },
  'API-USS016': { name: 'USER_ACTIVATION_CODE_INVALID', message: 'Activation code is invalid or already used', status: 400 },
  'API-USS017': { name: 'USER_VERIFICATION_CODE_RESEND_TOO_SOON', message: 'A verification code was sent recently', status: 429 },
  'API-USS018': { name: 'USER_VERIFICATION_ATTEMPTS_EXCEEDED', message: 'Too many verification attempts, request a new code', status: 429 },
  'API-USV001': { name: 'USER_EMAIL_INVALID', message: 'Invalid email format', status: 400 },
  'API-USV002': { name: 'USER_PASSWORD_TOO_WEAK', message: 'Password does not meet requirements', status: 400 },
  'API-USV003': { name: 'USER_PHONE_INVALID', message: 'Invalid phone number format', status: 400 },
  'API-USV004': { name: 'USER_AGE_REQUIREMENT_NOT_MET', message: 'Age requirement not met', status: 400 },
  'API-USV005': { name: 'USER_NICKNAME_TOO_LONG', message: 'Nickname exceeds maximum length', status: 400 },
  'API-USV006': { name: 'USER_INVALID_ACTIVITY_LEVEL', message: 'Invalid activity level', status: 400 },
  'API-USV007': { name: 'USER_INVALID_GOAL_TYPE', message: 'Invalid goal type', status: 400 },
  'API-USV008': { name: 'USER_PASSWORD_NOT_SET', message: 'Password not set (OAuth user)', status: 400 },
  'API-USV009': { name: 'USER_PASSWORD_INCORRECT', message: 'Incorrect password', status: 401 },
  'API-VCE001': { name: 'VOICE_NO_SPEECH_DETECTED', message: 'No speech detected in audio', status: 422 },
  'API-VCE002': { name: 'VOICE_TRANSCRIPTION_FAILED', message: 'Voice transcription failed', status: 502 },
  'API-VLU001': { name: 'VALIDATION_FAILED', message: 'Validation failed', status: 400 },
  'API-VLU002': { name: 'SERIALIZATION_FAILED', message: 'Data serialization failed', status: 500 },
  'API-VLU003': { name: 'DESERIALIZATION_FAILED', message: 'Data deserialization failed', status: 400 },
} as const

/** A known API error code string, e.g. `'API-BIS002'`. */
export type ApiErrorCode = keyof typeof API_ERROR_DEFINITIONS

/**
 * Ergonomic, autocompleted references to specific codes by their backend enum
 * name, e.g. `ApiErrorCodes.BILLING_INSUFFICIENT_CREDITS === 'API-BIS002'`.
 */
export const ApiErrorCodes = {
  AI_MODEL_UNAVAILABLE: 'API-AIS003',
  AI_RATE_LIMIT: 'API-AIS004',
  API_KEY_NOT_FOUND: 'API-AKR001',
  ARTICLE_ACCESS_DENIED: 'API-ATR002',
  ARTICLE_CREATION_FAILED: 'API-ATS001',
  ARTICLE_DELETION_FAILED: 'API-ATS004',
  ARTICLE_INVALID_INPUT: 'API-ATR003',
  ARTICLE_NOT_FOUND: 'API-ATR001',
  ARTICLE_PARSING_FAILED: 'API-ATS002',
  ARTICLE_UPDATE_FAILED: 'API-ATS003',
  ARTIFACT_CONTENT_NOT_TEXT: 'API-AFS002',
  ARTIFACT_CREATION_FAILED: 'API-AFS001',
  ARTIFACT_NOT_FOUND: 'API-AFR001',
  AUTH_CSRF_INVALID: 'API-AUR007',
  AUTH_CSRF_MISSING: 'API-AUR006',
  AUTH_PERMISSION_DENIED: 'API-AUR004',
  AUTH_RESOURCE_FORBIDDEN: 'API-AUR005',
  AUTH_SESSION_REQUIRED: 'API-AUR008',
  AUTH_TOKEN_EXPIRED: 'API-AUR003',
  AUTH_TOKEN_INVALID: 'API-AUR002',
  AUTH_TOKEN_MISSING: 'API-AUR001',
  BILLING_CHECKOUT_SESSION_NOT_FOUND: 'API-BIS013',
  BILLING_CUSTOMER_NOT_FOUND: 'API-BIS010',
  BILLING_DISCOUNT_CODE_ALREADY_REDEEMED: 'API-BIS008',
  BILLING_DISCOUNT_CODE_EXHAUSTED: 'API-BIS009',
  BILLING_DISCOUNT_CODE_EXPIRED: 'API-BIS007',
  BILLING_DISCOUNT_CODE_NOT_FOUND: 'API-BIS006',
  BILLING_INSUFFICIENT_CREDITS: 'API-BIS002',
  BILLING_INVALID_RETURN_URL: 'API-BIS011',
  BILLING_PAYMENT_PROCESSING_FAILED: 'API-BIS001',
  BILLING_PLAN_CHANGE_INVALID: 'API-BIS012',
  BILLING_PLAN_DOWNGRADE_NOT_SUPPORTED: 'API-BIS017',
  BILLING_PLAN_NOT_FOUND: 'API-BIS003',
  BILLING_PRODUCT_COST_NOT_FOUND: 'API-BIS005',
  BILLING_PROVIDER_NOT_ENABLED: 'API-BIC001',
  BILLING_PURCHASE_TOKEN_INVALID: 'API-BIS014',
  BILLING_PURCHASE_VERIFICATION_FAILED: 'API-BIS015',
  BILLING_SUBSCRIPTION_CONFLICT: 'API-BIS016',
  BILLING_SUBSCRIPTION_NOT_FOUND: 'API-BIS004',
  BILLING_WEBHOOK_EVENT_DUPLICATE: 'API-BIR002',
  BILLING_WEBHOOK_SIGNATURE_INVALID: 'API-BIR001',
  BRIGHTDATA_SCRAPE_FAILED: 'API-EXS008',
  CDN_SIGNER_UNAVAILABLE: 'API-CDN001',
  CLARIFICATION_CANCELLED: 'API-CVS015',
  CLARIFICATION_INVALID_RESPONSE: 'API-CVV007',
  CLARIFICATION_NOT_FOUND: 'API-CVS014',
  CLARIFICATION_RUN_INACTIVE: 'API-CVS016',
  COLLECTION_ACCESS_DENIED: 'API-CLR002',
  COLLECTION_ALREADY_EXISTS: 'API-CLR003',
  COLLECTION_CREATION_FAILED: 'API-CLS001',
  COLLECTION_DELETION_FAILED: 'API-CLS003',
  COLLECTION_NOT_FOUND: 'API-CLR001',
  COLLECTION_UPDATE_FAILED: 'API-CLS002',
  CONFIG_INVALID: 'API-CFC002',
  CONFIG_MISSING: 'API-CFC001',
  CONVERSATION_ACCESS_DENIED: 'API-CVR003',
  CONVERSATION_CREATION_FAILED: 'API-CVS001',
  CONVERSATION_DELETION_FAILED: 'API-CVS003',
  CONVERSATION_INVALID_CURSOR: 'API-CVR005',
  CONVERSATION_NAME_EMPTY: 'API-CVV002',
  CONVERSATION_NAME_TOO_LONG: 'API-CVV001',
  CONVERSATION_NO_ACTIVE_RUN: 'API-CVS017',
  CONVERSATION_NOT_FOUND: 'API-CVR001',
  CONVERSATION_RUN_IN_PROGRESS: 'API-CVS010',
  CONVERSATION_RUN_LOST: 'API-CVS018',
  CONVERSATION_SERVER_ERROR: 'API-CVV006',
  CONVERSATION_UPDATE_FAILED: 'API-CVS002',
  DB_CONNECTION_FAILED: 'API-DBC001',
  DB_CONSTRAINT_VIOLATION: 'API-DBM002',
  DB_CURSOR_INVALID_ORDER: 'API-DBC003',
  DB_QUERY_EXECUTION_FAILED: 'API-DBA007',
  DB_QUERY_INVALID_FILTER: 'API-DBA006',
  DB_QUERY_MIXED_FILTER_TABLES: 'API-DBA005',
  DB_QUERY_NOT_SELECT: 'API-DBA001',
  DB_QUERY_UNEXPECTED_ERROR: 'API-DBA008',
  DB_RECORD_NOT_FOUND: 'API-DBM003',
  DB_TABLE_PROHIBITED: 'API-DBA003',
  DB_TABLE_UNKNOWN: 'API-DBA004',
  DB_TIMEOUT: 'API-DBC002',
  DB_TRANSACTION_FAILED: 'API-DBM001',
  DEEPINFRA_ERROR: 'API-EXS006',
  DESERIALIZATION_FAILED: 'API-VLU003',
  DEVICE_NOT_FOUND: 'API-USS012',
  EXTERNAL_CONNECTION_ACCOUNT_UNAVAILABLE: 'API-ECS009',
  EXTERNAL_CONNECTION_AMBIGUOUS: 'API-ECS008',
  EXTERNAL_CONNECTION_DECRYPTION_FAILED: 'API-ECC001',
  EXTERNAL_CONNECTION_DISABLED: 'API-ECS005',
  EXTERNAL_CONNECTION_INVALID_CALLBACK: 'API-ECR003',
  EXTERNAL_CONNECTION_INVALID_GRANT: 'API-ECS004',
  EXTERNAL_CONNECTION_NOT_ACTIVE: 'API-ECS006',
  EXTERNAL_CONNECTION_NOT_FOUND: 'API-ECR002',
  EXTERNAL_CONNECTION_PROVIDER_NOT_REGISTERED: 'API-ECR001',
  EXTERNAL_CONNECTION_PROVIDER_REFRESH_FAILED: 'API-ECS003',
  EXTERNAL_CONNECTION_REFRESH_UNAVAILABLE: 'API-ECS007',
  EXTERNAL_CONNECTION_STATE_INVALID: 'API-ECS001',
  EXTERNAL_FILE_DOWNLOAD_FAILED: 'API-EXS007',
  EXTERNAL_IMAGE_DOWNLOAD_FAILED: 'API-EXS005',
  EXTERNAL_SERVICE_TIMEOUT: 'API-EXS004',
  FEISHU_CHAT_FAILED: 'API-FSS003',
  FEISHU_NO_SESSION: 'API-FSS004',
  FEISHU_SAVE_FAILED: 'API-FSS001',
  FEISHU_SEARCH_FAILED: 'API-FSS002',
  FEISHU_SIGNATURE_INVALID: 'API-FSR002',
  FEISHU_USER_NOT_LINKED: 'API-FSR001',
  FILE_DB_DELETE_FAILED: 'API-FLS004',
  FILE_DB_SAVE_FAILED: 'API-FLS003',
  FILE_EMPTY: 'API-FLV002',
  FILE_INVALID_FORMAT: 'API-FLR002',
  FILE_MISSING_PARAMETER: 'API-FLR003',
  FILE_NAME_INVALID: 'API-FLV004',
  FILE_NOT_FOUND: 'API-FLR001',
  FILE_NOT_FOUND_IN_S3: 'API-FLS006',
  FILE_NOT_REVISIONED: 'API-FLS010',
  FILE_REVISION_NOT_FOUND: 'API-FLS008',
  FILE_REVISION_NOT_OWNED: 'API-FLS009',
  FILE_S3_DELETE_FAILED: 'API-FLS005',
  FILE_S3_DOWNLOAD_FAILED: 'API-FLS002',
  FILE_S3_UPLOAD_FAILED: 'API-FLS001',
  FILE_SIZE_MISMATCH: 'API-FLS007',
  FILE_TOO_LARGE: 'API-FLV001',
  FILE_TYPE_NOT_ALLOWED: 'API-FLV003',
  FILE_UPLOAD_NOT_COMPLETABLE: 'API-FLV005',
  FRAME_EXTRACTION_FAILED: 'API-AIS008',
  GRAPH_EXECUTION_FAILED: 'API-GRS001',
  GRAPH_MAX_ITERATIONS_EXCEEDED: 'API-GRS003',
  GRAPH_NODE_TIMEOUT: 'API-GRS002',
  GRAPH_REQUEST_VALIDATION_FAILED: 'API-GRR001',
  IMAGE_DESCRIPTION_FAILED: 'API-AIS009',
  IMAGE_PROMPT_GENERATION_FAILED: 'API-IPS001',
  IMAGE_PROMPT_IN_PROGRESS: 'API-IPS002',
  IMG_PROMPT_ASSEMBLY_FAILED: 'API-IMG004',
  IMG_PROVIDER_FAILED: 'API-IMG002',
  IMG_REFERENCE_NOT_FOUND: 'API-IMG003',
  IMG_UNKNOWN_TAXONOMY: 'API-IMG001',
  INSIGHT_ACCESS_DENIED: 'API-INR002',
  INSIGHT_CREATION_FAILED: 'API-INS002',
  INSIGHT_GENERATION_FAILED: 'API-INS001',
  INSIGHT_INSUFFICIENT_DATA: 'API-INS003',
  INSIGHT_INVALID_TYPE: 'API-INR003',
  INSIGHT_NOT_FOUND: 'API-INR001',
  INSIGHT_UPDATE_FAILED: 'API-INS004',
  INTERNAL_VALIDATION_ERROR: 'API-INT001',
  KEYFRAME_EXTRACTION_FAILED: 'API-AIS007',
  LINKEDIN_CONTENT_UNAVAILABLE: 'API-EXS009',
  LLM_API_FAILURE: 'API-CVS009',
  LLM_STREAMING_ERROR: 'API-CVS008',
  MAIN_AGENT_BUDGET_EXHAUSTED: 'API-AIS013',
  MESSAGE_ACCESS_DENIED: 'API-CVR004',
  MESSAGE_CREATION_FAILED: 'API-CVS004',
  MESSAGE_DELETION_FAILED: 'API-CVS006',
  MESSAGE_EMPTY: 'API-CVV003',
  MESSAGE_HISTORY_RETRIEVAL_ERROR: 'API-CVS007',
  MESSAGE_INVALID_CURSOR: 'API-CVR006',
  MESSAGE_MENTION_LIMIT_EXCEEDED: 'API-CVS013',
  MESSAGE_MENTION_MIXED: 'API-CVS011',
  MESSAGE_MENTION_TOO_MANY_COLLECTIONS: 'API-CVS012',
  MESSAGE_NOT_FOUND: 'API-CVR002',
  MESSAGE_ROLE_INVALID: 'API-CVV004',
  MESSAGE_TOO_LONG: 'API-CVV005',
  MESSAGE_UPDATE_FAILED: 'API-CVS005',
  MULTIMODAL_EMBEDDING_FAILED: 'API-AIS011',
  NOTE_ACCESS_DENIED: 'API-NOR002',
  NOTE_COPY_FAILED: 'API-NOS005',
  NOTE_CREATION_FAILED: 'API-NOS001',
  NOTE_DELETION_FAILED: 'API-NOS004',
  NOTE_INVALID_INPUT: 'API-NOR003',
  NOTE_NOT_FOUND: 'API-NOR001',
  NOTE_PARSING_FAILED: 'API-NOS002',
  NOTE_UPDATE_FAILED: 'API-NOS003',
  NOTIFICATION_ACCESS_DENIED: 'API-NTR002',
  NOTIFICATION_DISABLED: 'API-NTS001',
  NOTIFICATION_NO_DEVICES: 'API-NTS003',
  NOTIFICATION_NOT_FOUND: 'API-NTR001',
  NOTIFICATION_SEND_FAILED: 'API-NTS002',
  OAUTH_EMAIL_MISSING: 'API-OAS005',
  OAUTH_INVALID_AUDIENCE: 'API-OAS008',
  OAUTH_INVALID_ISSUER: 'API-OAS007',
  OAUTH_INVALID_PROVIDER: 'API-OAS009',
  OAUTH_PROVIDER_ERROR: 'API-OAS003',
  OAUTH_PROVIDER_NOT_CONFIGURED: 'API-OAS006',
  OAUTH_TOKEN_EXPIRED: 'API-OAS002',
  OAUTH_TOKEN_INVALID: 'API-OAS001',
  OAUTH_VERIFICATION_FAILED: 'API-OAS004',
  OAUTH2_ACCESS_DENIED: 'API-O2R006',
  OAUTH2_INVALID_CLIENT: 'API-O2R001',
  OAUTH2_INVALID_CLIENT_SECRET: 'API-O2S003',
  OAUTH2_INVALID_GRANT: 'API-O2S001',
  OAUTH2_INVALID_REDIRECT_URI: 'API-O2R002',
  OAUTH2_INVALID_REQUEST: 'API-O2R003',
  OAUTH2_INVALID_STATE: 'API-O2R005',
  OAUTH2_PKCE_VERIFICATION_FAILED: 'API-O2S002',
  OAUTH2_UNSUPPORTED_GRANT_TYPE: 'API-O2R004',
  OCR_AGENT_FAILED: 'API-AIS001',
  ONBOARDING_REWARD_ALREADY_CLAIMED: 'API-ONS002',
  ONBOARDING_TASK_NOT_COMPLETED: 'API-ONS001',
  PINNED_ITEM_ALREADY_EXISTS: 'API-PIR002',
  PINNED_ITEM_INVALID_INPUT: 'API-PIR003',
  PINNED_ITEM_NOT_FOUND: 'API-PIR001',
  PLAN_AGENT_BUDGET_EXHAUSTED: 'API-AIS012',
  PPT_GAMMA_DISABLED: 'API-PPC001',
  PPT_GAMMA_DOWNLOAD_FAILED: 'API-PPS004',
  PPT_GAMMA_SUBMIT_FAILED: 'API-PPS001',
  PPT_GAMMA_TIMEOUT: 'API-PPS003',
  PYDANTIC_FIELD_REQUIRED: 'API-PYV002',
  PYDANTIC_TYPE_ERROR: 'API-PYV003',
  PYDANTIC_VALIDATION_ERROR: 'API-PYV001',
  PYDANTIC_VALUE_ERROR: 'API-PYV004',
  RECOMMENDATION_GENERATION_FAILED: 'API-RCS001',
  RECOMMENDATION_NOT_FOUND: 'API-RCR001',
  RECOMMENDATION_SEARCH_FAILED: 'API-RCS002',
  S3_ACCESS_DENIED: 'API-S3C003',
  S3_BUCKET_NOT_FOUND: 'API-S3C002',
  S3_CONNECTION_FAILED: 'API-S3C001',
  SERIALIZATION_FAILED: 'API-VLU002',
  SKILL_INVALID_FILE: 'API-SLS002',
  SKILL_INVALID_OWNERSHIP: 'API-SLS003',
  SKILL_NOT_FOUND: 'API-SLS001',
  SLACK_CHAT_FAILED: 'API-SKS004',
  SLACK_LINK_FAILED: 'API-SKS001',
  SLACK_NO_SESSION: 'API-SKS005',
  SLACK_SAVE_FAILED: 'API-SKS002',
  SLACK_SEARCH_FAILED: 'API-SKS003',
  SLACK_USER_NOT_LINKED: 'API-SKR001',
  SUGGESTION_ACCESS_DENIED: 'API-SUR002',
  SUGGESTION_CLASSIFICATION_FAILED: 'API-SUS001',
  SUGGESTION_INVALID_STATUS: 'API-SUR003',
  SUGGESTION_NOT_FOUND: 'API-SUR001',
  SUGGESTION_STATUS_CONFLICT: 'API-SUR004',
  TAG_ALREADY_EXISTS: 'API-TGR002',
  TAG_CREATION_FAILED: 'API-TGS001',
  TAG_DELETION_FAILED: 'API-TGS002',
  TAG_GENERATION_FAILED: 'API-AIS010',
  TAG_INVALID_INPUT: 'API-TGR003',
  TAG_NOT_FOUND: 'API-TGR001',
  TEXT_EMBEDDING_FAILED: 'API-TXS002',
  TEXT_EMPTY: 'API-TXR001',
  TEXT_INVALID_SOURCE_ID: 'API-TXR002',
  TEXT_MILVUS_INSERT_FAILED: 'API-TXS003',
  TEXT_SELECTION_FAILED: 'API-TSS001',
  TEXT_SPLITTING_FAILED: 'API-TXS001',
  USER_ACCOUNT_DISABLED: 'API-USR005',
  USER_ACCOUNT_NOT_ACTIVATED: 'API-USR010',
  USER_ACTIVATION_CODE_INVALID: 'API-USS016',
  USER_ACTIVATION_CODE_REQUIRED: 'API-USS015',
  USER_AGE_REQUIREMENT_NOT_MET: 'API-USV004',
  USER_ALREADY_ACTIVATED: 'API-USR011',
  USER_ALREADY_EXISTS: 'API-USR002',
  USER_CLIENT_IP_UNAVAILABLE: 'API-USC001',
  USER_DELETE_FAILED: 'API-USS011',
  USER_DEMOGRAPHIC_NOT_FOUND: 'API-USR007',
  USER_EMAIL_INVALID: 'API-USV001',
  USER_EMAIL_NOT_VERIFIED: 'API-USR003',
  USER_EMAIL_SEND_FAILED: 'API-USS004',
  USER_INVALID_ACTIVITY_LEVEL: 'API-USV006',
  USER_INVALID_CREDENTIALS: 'API-USR004',
  USER_INVALID_GOAL_TYPE: 'API-USV007',
  USER_INVITATION_CODE_INVALID: 'API-USS013',
  USER_INVITATION_LIMIT_REACHED: 'API-USS014',
  USER_NICKNAME_TOO_LONG: 'API-USV005',
  USER_NOT_FOUND: 'API-USR001',
  USER_OAUTH_REQUIRED: 'API-USR009',
  USER_PASSWORD_HASH_FAILED: 'API-USS002',
  USER_PASSWORD_INCORRECT: 'API-USV009',
  USER_PASSWORD_NOT_SET: 'API-USV008',
  USER_PASSWORD_TOO_WEAK: 'API-USV002',
  USER_PHONE_INVALID: 'API-USV003',
  USER_PREFERENCES_NOT_FOUND: 'API-USR008',
  USER_REFRESH_TOKEN_EXPIRED: 'API-USS009',
  USER_REFRESH_TOKEN_INVALID: 'API-USS008',
  USER_REGISTRATION_FAILED: 'API-USS001',
  USER_SESSION_EXPIRED: 'API-USS007',
  USER_SESSION_NOT_FOUND: 'API-USR006',
  USER_TOKEN_GENERATION_FAILED: 'API-USS003',
  USER_UPDATE_FAILED: 'API-USS010',
  USER_VERIFICATION_ATTEMPTS_EXCEEDED: 'API-USS018',
  USER_VERIFICATION_CODE_EXPIRED: 'API-USS005',
  USER_VERIFICATION_CODE_INVALID: 'API-USS006',
  USER_VERIFICATION_CODE_RESEND_TOO_SOON: 'API-USS017',
  VALIDATION_FAILED: 'API-VLU001',
  VOICE_NO_SPEECH_DETECTED: 'API-VCE001',
  VOICE_TRANSCRIPTION_FAILED: 'API-VCE002',
} as const satisfies Record<string, ApiErrorCode>

/** Module-code legend (the `XX` segment of a code → what subsystem it belongs to). */
export const API_ERROR_MODULES: Record<string, string> = {
  'FL': 'File operations',
  'AU': 'Authentication',
  'US': 'User management',
  'CV': 'Conversation operations',
  'NT': 'Notification operations',
  'IN': 'Insight operations',
  'AT': 'Article operations',
  'NO': 'Note operations',
  'TG': 'Tag operations',
  'CL': 'Collection operations',
  'SU': 'Collection suggestion operations',
  'TX': 'Text/RAG operations',
  'DB': 'Database',
  'S3': 'S3/Storage',
  'EX': 'External services',
  'AI': 'AI/Agent operations',
  'IMG': 'Image generation',
  'CF': 'Configuration',
  'VL': 'Validation utilities',
  'GR': 'Graph agent operations',
  'SK': 'Slack integration',
  'FS': 'Feishu integration',
  'O2': 'OAuth2 authorization server',
  'EC': 'External-connection (third-party OAuth credentials)',
  'PP': 'PPT/Presentation generation',
  'AF': 'Artifact operations',
  'BI': 'Billing / subscription / payment operations',
  'RC': 'Recommendation operations',
  'SL': 'Dynamic skill operations',
  'ON': 'User-onboarding checklist',
  'TS': 'Text-selection toolbar actions (explain / summarize / translate)',
  'PYV': 'Pydantic validation (request errors)',
  'INT': 'Internal server errors',
}

/** Layer-code legend (the `Y` segment of a code → which layer raised it). */
export const API_ERROR_LAYERS: Record<string, string> = {
  'R': 'Router/Controller layer',
  'S': 'Service layer',
  'M': 'Model/Database layer',
  'C': 'Context/Infrastructure layer',
  'U': 'Utility/Helper layer',
  'V': 'Validation/Schema layer',
}

/** Resolve a code string to its canonical {@link ApiErrorDefinition}, if known. */
export function getErrorDefinition(code: string | undefined | null): ApiErrorDefinition | undefined {
  if (!code) return undefined
  return (API_ERROR_DEFINITIONS as Record<string, ApiErrorDefinition>)[code]
}

/** Split a code into its module / layer / sequence parts, e.g. `API-BIS002` → `{ module: 'BI', layer: 'S', sequence: '002' }`. */
export function parseErrorCode(
  code: string | undefined | null
): { module: string; moduleName?: string; layer: string; layerName?: string; sequence: string } | undefined {
  if (!code) return undefined
  const m = /^API-([A-Z]{2,3})([A-Z])(\d{3})$/.exec(code)
  const mod = m?.[1]
  const layer = m?.[2]
  const sequence = m?.[3]
  if (mod === undefined || layer === undefined || sequence === undefined) return undefined
  return {
    module: mod,
    moduleName: API_ERROR_MODULES[mod],
    layer,
    layerName: API_ERROR_LAYERS[layer],
    sequence,
  }
}
